name: quantum-ml-dd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - ase
  - rdkit
  - pyscf
  - xtb-python
  - pytorch
  - pytorch-geometric
  - e3nn
  - jupyter
  - pytest
  - pip:
      - -e .
